version: 2.1
orbs:
  datree: naorpeled/datree@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
    command-tests:
      executor: datree/default

      environment:
        - name: DATREE_TOKEN
          value: $DATREE_TOKEN

      steps:
        - checkout
        - datree/test:
            path: "./tests-data/sample-policy.yaml"
            cliArguments: "--output=json"
        - datree/test:
            path: "./tests-data/sample-helm-policy"
            isHelmChart: true
            helmArguments: "--output=json"
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - command-tests:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: naorpeled/datree
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
