description: >
  Docker executor with Datree CLI installed
docker:
  - image: cimg/base:current
  - image: datree/datreeci:<<parameters.cli-version>>
parameters:
  cli-version:
    default: latest
    description: >
      Pick a specific datree image variant
    type: string
