description: >
  Docker executor with Datree CLI installed
docker:
  - image: 'datree/datree:<<parameters.cli-version>>'
parameters:
  cli-version:
    default: latest
    description: >
      Pick a specific datree image variant
    type: string
