description: >
  A demonstration of how to run a Kustomization policy check.

usage:
  version: 2.1
  orbs:
    datree: datree/datree@1.1.9

  workflows:
    policy-check:
      jobs:
        - datree/policy-check:
            path: 'someDirectory/someKustomizationFolder'
            isKustomization: true
            cliArguments: '--schema-version 1.20.0'
